import type { ServiceProvider } from '@/types';

export const providers: ServiceProvider[] = [
  {
    id: 'p1',
    name: 'Carlos Mendes',
    serviceType: 'Eletricista',
    rating: 4.8,
    reviewsCount: 127,
    location: 'Centro, São Paulo',
    distanceKm: 1.2,
    estimatedArrivalMin: 15,
    description: 'Eletricista certificado com mais de 10 anos de experiência em instalações residenciais e comerciais.',
    lat: -23.5505,
    lng: -46.6333,
    avatarUrl: 'https://i.pravatar.cc/150?img=12',
    startingPrice: 80,
  },
  {
    id: 'p2',
    name: 'Ana Ribeiro',
    serviceType: 'Encanador',
    rating: 4.6,
    reviewsCount: 89,
    location: 'Vila Mariana, São Paulo',
    distanceKm: 3.5,
    estimatedArrivalMin: 25,
    description: 'Especialista em reparos hidráulicos, detecção de vazamentos e manutenção preventiva.',
    lat: -23.5878,
    lng: -46.6342,
    avatarUrl: 'https://i.pravatar.cc/150?img=45',
    startingPrice: 90,
  },
  {
    id: 'p3',
    name: 'Rafael Souza',
    serviceType: 'Técnico de computador',
    rating: 4.9,
    reviewsCount: 203,
    location: 'Pinheiros, São Paulo',
    distanceKm: 5.0,
    estimatedArrivalMin: 35,
    description: 'Suporte técnico, formatação, remoção de vírus e montagem de PCs. Atendimento remoto e presencial.',
    lat: -23.5705,
    lng: -46.6975,
    avatarUrl: 'https://i.pravatar.cc/150?img=33',
    startingPrice: 60,
  },
  {
    id: 'p4',
    name: 'Mariana Costa',
    serviceType: 'Fotógrafo',
    rating: 5.0,
    reviewsCount: 156,
    location: 'Jardins, São Paulo',
    distanceKm: 4.2,
    estimatedArrivalMin: 40,
    description: 'Fotografia de eventos, retratos e produtos. Equipamento profissional e edição inclusa.',
    lat: -23.5675,
    lng: -46.6588,
    avatarUrl: 'https://i.pravatar.cc/150?img=20',
    startingPrice: 200,
  },
  {
    id: 'p5',
    name: 'João Pereira',
    serviceType: 'Professor particular',
    rating: 4.7,
    reviewsCount: 78,
    location: 'Moema, São Paulo',
    distanceKm: 6.1,
    estimatedArrivalMin: 45,
    description: 'Aulas de matemática e física para ensino fundamental e médio. Aulas particulares e em grupo.',
    lat: -23.5989,
    lng: -46.6578,
    avatarUrl: 'https://i.pravatar.cc/150?img=51',
    startingPrice: 50,
  },
  {
    id: 'p6',
    name: 'Beatriz Lima',
    serviceType: 'Designer',
    rating: 4.8,
    reviewsCount: 112,
    location: 'Santa Cecília, São Paulo',
    distanceKm: 2.8,
    estimatedArrivalMin: 20,
    description: 'Design gráfico, branding e identidade visual. Criação de logotipos, flyers e materiais digitais.',
    lat: -23.5362,
    lng: -46.6488,
    avatarUrl: 'https://i.pravatar.cc/150?img=47',
    startingPrice: 120,
  },
  {
    id: 'p7',
    name: 'Patricia Nunes',
    serviceType: 'Manicure',
    rating: 4.9,
    reviewsCount: 234,
    location: 'Liberdade, São Paulo',
    distanceKm: 3.0,
    estimatedArrivalMin: 22,
    description: 'Manicure e pedicure com técnicas avançadas. Atendimento a domicílio com produtos de qualidade.',
    lat: -23.5587,
    lng: -46.6345,
    avatarUrl: 'https://i.pravatar.cc/150?img=24',
    startingPrice: 40,
  },
  {
    id: 'p8',
    name: 'Lucas Ferreira',
    serviceType: 'Personal trainer',
    rating: 4.7,
    reviewsCount: 98,
    location: 'Itaim Bibi, São Paulo',
    distanceKm: 5.5,
    estimatedArrivalMin: 30,
    description: 'Personal trainer certificado. Treinos personalizados, acompanhamento nutricional e avaliação física.',
    lat: -23.5825,
    lng: -46.6772,
    avatarUrl: 'https://i.pravatar.cc/150?img=15',
    startingPrice: 100,
  },
  {
    id: 'p9',
    name: 'Fernanda Alves',
    serviceType: 'Outros serviços',
    rating: 4.5,
    reviewsCount: 56,
    location: 'Bela Vista, São Paulo',
    distanceKm: 4.0,
    estimatedArrivalMin: 30,
    description: 'Diarista e organizadora profissional. Limpeza residencial, organização de ambientes e mudanças.',
    lat: -23.5586,
    lng: -46.6609,
    avatarUrl: 'https://i.pravatar.cc/150?img=31',
    startingPrice: 70,
  },
  {
    id: 'p10',
    name: 'Roberto Silva',
    serviceType: 'Eletricista',
    rating: 4.5,
    reviewsCount: 67,
    location: 'Lapa, São Paulo',
    distanceKm: 7.0,
    estimatedArrivalMin: 50,
    description: 'Instalação de chuveiros, troca de quadros de distribuição e manutenção de circuitos.',
    lat: -23.5062,
    lng: -46.7036,
    avatarUrl: 'https://i.pravatar.cc/150?img=53',
    startingPrice: 75,
  },
  {
    id: 'p11',
    name: 'Juliana Rocha',
    serviceType: 'Encanador',
    rating: 4.4,
    reviewsCount: 41,
    location: 'Sé, São Paulo',
    distanceKm: 2.0,
    estimatedArrivalMin: 18,
    description: 'Desentupimento de ralos e pias, instalação de vasos e torneiras. Atendimento de emergência.',
    lat: -23.5503,
    lng: -46.6378,
    avatarUrl: 'https://i.pravatar.cc/150?img=44',
    startingPrice: 85,
  },
  {
    id: 'p12',
    name: 'Gustavo Henrique',
    serviceType: 'Técnico de computador',
    rating: 4.6,
    reviewsCount: 73,
    location: 'Perdizes, São Paulo',
    distanceKm: 6.5,
    estimatedArrivalMin: 40,
    description: 'Especialista em redes, configuração de roteadores e recuperação de dados.',
    lat: -23.5342,
    lng: -46.6939,
    avatarUrl: 'https://i.pravatar.cc/150?img=60',
    startingPrice: 65,
  },
];

export const heroImage =
  'https://images.pexels.com/photos/7641255/pexels-photo-7641255.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';

export const aboutImage =
  'https://img.magnific.com/fotos-premium/profissionais-diversos-conectados-colaborando-online_53876-1119544.jpg?semt=ais_hybrid&w=740&q=80';
